### ISSUE TITLE
#US11 Iniciar Sesión

### ISSUE THREAD

**Issue by Jesica-A** [Desarrollo-Web-2024-segundo-intento/Proyecto-Integrador-II#34]
### HISTORIA DE USUARIO:
**Como** usuario **quiero** poder iniciar sesión **para** usar las funcionalidades del sistema

### CRITERIO DE ACEPTACIÓN:
1.	El usuario debe estar previamente registrado
2.	El formulario de inicio de sesión debe contener los siguientes campos:
•	Email
•	Contraseña
•	Botón “iniciar sesión”
3.	Validaciones de los campos:
•	Email: formato [aaa@aaa.com](mailto:aaa@aaa.com) y además que el email exista en la base de datos
•	Contraseña: que coincida con la contraseña para el usuario registrado con el email proporcionado en el campo anterior
4.	Link/botón “¿Olvidó su contraseña?"

### TASK:
- [ ] Diseñar
- [ ] Escribir  HTML
- [ ] Diseño Responsive (CSS/Bootstrap)
- [ ] Validaciones de formulario con Javascript
- [ ] Usuario en base de datos
- [ ] Testear
