### ISSUE TITLE
#US14 Cambiar información de Perfil

### ISSUE THREAD

**Issue by Jesica-A** [Desarrollo-Web-2024-segundo-intento/Proyecto-Integrador-II#37]
### HISTORIA DE USUARIO:
Como usuario quiero poder cambiar mi información en el perfil de usuario para mantener actualizada mi información

### CRITERIOS DE ACEPTACION:
1.	El usuario logueado podrá cambiar sus datos en la sección “Perfil” mediante el link/botón “Modificar datos”
2.	El usuario visualizará sus datos en forma de formulario donde podrá cambiarlos 
3.	Se deberán guardar los cambios cuando se dé clic en el botón “guardar” al final del formulario

### TASKS:
- [ ] Diseñar
- [ ] Escribir  HTML 
- [ ] Diseño Responsive (CSS/Bootstrap)
- [ ] Validacion con Javascript
- [ ] Modificacion de informacion en base de datos
- [ ] Testear
